### ISSUE TITLE
Keypress Library update

### ISSUE THREAD

**Issue by santilland** [v-manip/WebClient-Framework#15]
Since release 2.0 of keypress (20.01.2014) it seems it has to be instantiated in some form, which creates an error on the client (combo method not defined). In the bower components the version is marked with \* installing always the latest release. On the branch i am working on i limited it to 1.x with:
"Keypress": "~1.0.9"
, which at some point will be merged to master. Do we want to update to 2.x? We will have to fix the issue.

**Comment by martinhecher** [comment]
I updated the code to the latest API changes. So we can stick with the most current version.

The fix is in master as of now.
