### ISSUE TITLE
Buttons not shown on mobile clients

### ISSUE THREAD

**Issue by Schpidi** [v-manip/WebClient-Framework#19]

**Comment by Schpidi** [comment]
![screenshot_2014-04-09-14-06-37](https://cloud.githubusercontent.com/assets/482265/2681807/b936a92e-c191-11e3-92af-bba2a06e2c8b.png)

**Comment by santilland** [comment]
The problem was due to a missing button in the header. This has been solved in the commit 1a15885189b9856ae3e2f13e823ec4183e3e7c60
