### ISSUE TITLE
Possibility to deactivate the selection tool

### ISSUE THREAD

**Issue by martinhecher** [v-manip/WebClient-Framework#9]
Currently when a selection tool is selected in the 'Tools' panel it is not possible to deactivate the selection tool again.

**Comment by santilland** [comment]
Can't reproduce bug, when activating a selection tool i can deactivate it by clicking it again. Is this still up to date? If yes, on what browser?

**Comment by martinhecher** [comment]
Sorry, my bad. Deselection works as expected.
